version: "3"
services:
  mysql:
    image: wings-mysql-img
    build: ./mysql
    container_name: wings-mysql-ctr
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=wings
      - MYSQL_ROOT_PASSWORD=P@ssw0rd!
